name: Create and Publish FlexGet Docker Image
on: [ push, pull_request ]
jobs:
  build-linux-amd64-image:
    name: Build linux/amd64 image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/flexget
            ghcr.io/${{ github.repository_owner }}/flexget
          flavor: suffix=-linux-amd64
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=edge
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build linux/amd64 image
        uses: docker/bake-action@v2.0.0
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: linux-amd64
  build-linux-arm64-image:
    name: Build linux/arm64 image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/flexget
            ghcr.io/${{ github.repository_owner }}/flexget
          flavor: suffix=-linux-arm64
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=edge
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build linux/arm64 image
        uses: docker/bake-action@v2.0.0
        with:
          push: true
          files: |
            ./docker-bake.hcl
            ${{ steps.meta.outputs.bake-file }}
          targets: linux-arm64
  publish-image:
    name: Publish FlexGet image
    runs-on: ubuntu-latest
    needs:
      - build-linux-amd64-image
      - build-linux-arm64-image
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/flexget
            ghcr.io/${{ github.repository_owner }}/flexget
          flavor: suffix=linux-amd64
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=edge
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Build and push a FlexGet Docker image
        run: |
          IFS=',' read -ra ADDR <<< ${{ steps.meta.outputs.tags }}
          for i in "${ADDR[@]}"; do
            docker manifest create $i --amend $i-amd64 --amend $i-linux-arm64
            docker push $i
          done
